# Generated by Django 4.0.5 on 2022-07-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profile_pic', models.ImageField(null=True, upload_to='media/images/profileImages')),
            ],
        ),
    ]
