# Generated by Django 4.0.5 on 2022-07-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('longDesc', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(max_length=200)),
                ('roadInFront', models.BooleanField(default=False)),
                ('distanceFromHighway', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('bedroom', models.IntegerField(default=0)),
                ('hall', models.IntegerField(default=0)),
                ('garage', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('cardImage', models.ImageField(null=True, upload_to='media/images/cardImages')),
                ('coverImage', models.ImageField(null=True, upload_to='media/images/coverImages')),
                ('featured', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
    ]
